export const TOUR_CAPACITY = 25;
export const DEFAULT_TOUR_MINIMUM = 20;
export const DEFAULT_TOUR_PRICE_CENTS = 2000;
export const DEFAULT_TOUR_BOOKING_CUTOFF_HOURS = 24;
export const TOUR_MINIMUM = DEFAULT_TOUR_MINIMUM;
