import Image from "next/image";
import Link from "next/link";
import { BeerCard } from "@/components/cards";
import { CouponSpotlight } from "@/components/coupons";
import { BeerReleaseAlertBand } from "@/components/beer-release-alert";
import { HomeLogoViewer } from "@/components/home-logo-viewer";
import { LocationCard } from "@/components/location-card";
import { InquiryForm } from "@/components/inquiry-form";
import { ArrowUpRight, MapPin } from "@/components/icons";
import { orderFoodUrl } from "@/data/site";
import { getAllBeers } from "@/lib/managed-beers";
import { getAllLocations } from "@/lib/managed-locations";
import { getPublishedEvents, type ManagedEvent } from "@/lib/managed-events";
import { couponAvailability, getCouponOffers } from "@/lib/coupons";
import { getBeerReleaseAlert } from "@/lib/beer-release-alert";

export const dynamic = "force-dynamic";

function formatManagedDate(date: string) {
  return new Intl.DateTimeFormat("en-US", { weekday: "short", month: "short", day: "numeric", timeZone: "America/New_York" }).format(new Date(`${date}T12:00:00-05:00`));
}

function formatManagedTime(time: string) {
  const [hour, minute] = time.split(":").map(Number);
  return new Intl.DateTimeFormat("en-US", { hour: "numeric", minute: "2-digit" }).format(new Date(2020, 0, 1, hour, minute));
}

function ManagedEventCard({ event }: { event: ManagedEvent }) {
  return <article className="event-card managed-event-card"><div className="event-date"><span>{formatManagedDate(event.date)}</span><strong>{formatManagedTime(event.startTime)}{event.endTime ? `-${formatManagedTime(event.endTime)}` : ""}</strong></div><div className="event-content"><p className="card-kicker">{event.location}</p><h3>{event.title}</h3><p className="managed-event-copy">{event.description}</p>{event.ticketUrl ? <a href={event.ticketUrl} target="_blank" rel="noreferrer" data-analytics="home_managed_event_tickets">Details + tickets <ArrowUpRight /></a> : <Link href="/events" data-analytics="home_managed_event_calendar">Event details <ArrowUpRight /></Link>}</div></article>;
}

export default async function Home() { const [weekendEvents, locations, beers, couponOffers, couponStatus, beerReleaseAlert] = await Promise.all([getPublishedEvents({ monthsAhead: 2 }), getAllLocations(), getAllBeers(), getCouponOffers(), couponAvailability(), getBeerReleaseAlert()]); const schema = { "@context": "https://schema.org", "@type": ["Brewery", "Restaurant", "LocalBusiness"], name: "Aviator Brewing Company", address: { "@type": "PostalAddress", streetAddress: "688 Brewing Drive", addressLocality: "Fuquay-Varina", addressRegion: "NC", postalCode: "27526", addressCountry: "US" }, telephone: "+1-919-567-2337", servesCuisine: ["American", "Pizza", "Barbecue"], url: "https://aviatorbrew.com" }; return <>
  <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
  <section className="hero hero-runway"><div className="hero-media"><Image src="/images/hero-runway-wwii-restored.png" alt="Aviator field runway leading to a glowing brewery hangar at dusk" fill priority unoptimized sizes="100vw" /></div><div className="hero-p51" aria-hidden="true"><Image src="/images/p51-strafing-hero-restored.png" alt="" fill priority unoptimized sizes="100vw" /></div><span className="flight-path" aria-hidden="true" /><span className="runway-number" aria-hidden="true">08<span>26</span></span><div className="hero-content"><HomeLogoViewer /><p className="eyebrow">Aviator Field · Fuquay-Varina, North Carolina · Est. 2008</p><h1>Your next <em>adventure</em> is brewing.</h1><p className="hero-copy">Craft beer, scratch-made food, live music, events, weekend brunch, cocktails, and aviation-inspired experiences—built for a great night out.</p><div className="hero-actions"><a className="button button-order-food" href={orderFoodUrl} data-analytics="hero_order_food">Order food <ArrowUpRight /></a><Link className="button button-outline" href="/brewery" data-analytics="hero_explore_brewery">Enter the hangar <ArrowUpRight /></Link><Link className="button button-outline" href="/locations" data-analytics="hero_view_locations">View locations</Link><Link className="button button-outline" href="/events" data-analytics="hero_events">See what&apos;s happening</Link></div><div className="flight-data" aria-label="Aviator field information"><span>FIELD <b>FVNC</b></span><span>RUNWAY <b>08 / 26</b></span><span>OPEN <b>7 DAYS</b></span></div></div></section>
  <section className="hangar-waitlist"><div className="content-wrap hangar-waitlist-inner"><div><p className="eyebrow">Aviator Hangar Bar / 688 Brewing Drive</p><h2>Want a table? <em>Join the waitlist.</em></h2><p>Planning a stop at the Hangar Bar? Add your party to the waitlist before you arrive.</p></div><a className="button button-light" href="https://www.waitlist.me/w/aviatorhangarbar" target="_blank" rel="noreferrer" data-analytics="hangar_bar_waitlist">Join Hangar Bar waitlist <ArrowUpRight /></a></div></section>
  <div className="arrival-strip" aria-label="Aviator field updates"><div className="arrival-track"><span>Now boarding: great beer</span><i>✦</i><span>Live music on the field</span><i>✦</i><span>BEER IS MY FRIEND</span><i>✦</i><span>Private events cleared for takeoff</span><i>✦</i><span>Now boarding: great beer</span><i>✦</i><span>Live music on the field</span><i>✦</i><span>BEER IS MY FRIEND</span><i>✦</i><span>Private events cleared for takeoff</span></div></div>
  <BeerReleaseAlertBand alert={beerReleaseAlert} />
  {couponOffers.length ? <CouponSpotlight offers={couponOffers} allowed={couponStatus.allowed} reason={couponStatus.reason} /> : null}
  <section id="updates" className="home-newsletter-signup"><div className="content-wrap"><div className="newsletter"><div><p className="eyebrow">Join the Flight Crew</p><h2>Beer releases, music, and events. Straight to your inbox.</h2><p>Get new beers, weekend plans, restaurant news, concerts, and offers from across Aviator. We will email you a quick confirmation link to make sure the address is yours.</p></div><InquiryForm kind="newsletter" /></div></div></section>
  <section className="section campus-directory-section"><div className="content-wrap"><div className="section-heading"><div><p className="eyebrow">The Aviator campus</p><h2>More than a brewery. <em>A whole way to spend the day.</em></h2></div><p>From a first pint to a late cocktail, each Aviator landing spot has its own food, mood, hours, and reason to stay a little longer.</p></div><div className="campus-dispatch"><div><span>07</span><strong>Places to land</strong><p>Pick a room, check its hours, then make a plan.</p></div><div><span>01</span><strong>One field command</strong><p>Campus favorites, downtown stops, music, food, beer, and more.</p></div><Link className="section-link" href="/locations">Open the full location guide <ArrowUpRight /></Link></div><div className="location-grid campus-location-grid">{locations.map((location) => <LocationCard key={location.slug} location={location} />)}</div><div className="hero-actions"><Link className="button" href="/locations#menus" data-analytics="campus_view_menus">Find food + drinks <ArrowUpRight /></Link><a className="button button-outline" target="_blank" rel="noreferrer" href="https://maps.google.com/?q=688+Brewing+Drive+Fuquay-Varina+NC+27526" data-analytics="campus_directions"><MapPin />Get directions</a></div></div></section>

  <section className="beer-stage"><div className="content-wrap"><div className="section-heading"><div><p className="eyebrow">Featured beers</p><h2>Flight-tested, <em>fresh-poured.</em></h2></div><Link className="section-link" href="/beer">Browse all beer <ArrowUpRight /></Link></div><div className="beer-grid">{beers.slice(0, 4).map((beer) => <BeerCard key={beer.slug} beer={beer} />)}</div></div></section>
  <section className="section"><div className="content-wrap food-grid"><div className="food-image"><Image src="/images/food.jpg" alt="Scratch-made Aviator food" fill unoptimized sizes="(max-width: 700px) 100vw, 50vw" /></div><div className="food-content"><p className="eyebrow">Eat + drink</p><h2 className="display-title">Come hungry. <em>Stay late.</em></h2><p>Weekend brunch, burgers, wings, pizza, steaks, chef specials, cocktails, and whiskey—built around the kind of table you don&apos;t rush away from.</p><div className="food-list"><span>Weekend Brunch</span><span>Brick-oven Pizza</span><span>Burgers + Wings</span><span>Steaks + Specials</span><span>Craft Cocktails</span><span>Whiskey + Spirits</span></div><Link className="button" href="/locations#menus" data-analytics="home_view_menus">View menus <ArrowUpRight /></Link></div></div></section>
  <section className="section section-dark"><div className="content-wrap"><div className="section-heading"><div><p className="eyebrow">Live music + events</p><h2>Make the weekend <em>take off.</em></h2></div><Link className="section-link" href="/events">Full events calendar <ArrowUpRight /></Link></div>{weekendEvents.length ? <div className="event-layout managed-event-layout">{weekendEvents.map((event) => <ManagedEventCard key={event.id} event={event} />)}</div> : <div className="event-layout event-empty"><article className="event-card managed-event-card"><div className="event-date"><span>Stand by</span><strong>Next 2 months</strong></div><div className="event-content"><h3>New events are being cleared.</h3><p>No special events are currently published for the next two months. Check the full calendar for live music and other updates.</p><Link href="/events">Full events calendar <ArrowUpRight /></Link></div></article></div>}</div></section>
  <section className="night-ops"><div className="night-ops-image"><Image src="/images/ready-room-after-dark.png" alt="Warm aviation-inspired cocktail lounge at Aviator after dark" fill sizes="(max-width: 760px) 100vw, 60vw" /></div><div className="night-ops-copy"><p className="eyebrow">After dark · Flight 70</p><h2>The lights stay on <em>after the last note.</em></h2><p>Slip into the Ready Room, make a night of the Speakeasy, or turn your next gathering into something people talk about on the ride home.</p><dl className="night-ops-spec"><div><dt>Ready Room</dt><dd>Private events · 70 guests including bar</dd></div><div><dt>Speakeasy</dt><dd>Whiskey, cocktails, and a little mystery</dd></div><div><dt>Field command</dt><dd>688 Brewing Drive · Fuquay-Varina</dd></div></dl><div className="hero-actions"><Link className="button" href="/locations/ready-room" data-analytics="night_ops_ready_room">Explore the Ready Room <ArrowUpRight /></Link><Link className="button button-outline" href="/private-events" data-analytics="night_ops_events">Plan an event</Link></div></div></section>
  <section className="section"><div className="content-wrap split-content"><div><p className="eyebrow">Brewery experience</p><h2>Built here. Poured here. <em>Enjoyed here.</em></h2></div><div><p>Aviator began in a small airplane hangar in 2008. From early batches in repurposed dairy tanks to a new brewery campus built for beer, food, music, and community, the mission has stayed the same: make something people want to come back for.</p><div className="story-timeline"><div><strong>2008</strong><span>One brewer, two tanks, and a small airplane hangar.</span></div><div><strong>2009</strong><span>The original TapHouse opens in historic Varina.</span></div><div><strong>2025</strong><span>The new brewery campus opens a new chapter for Aviator.</span></div></div><Link className="section-link" href="/about">Our full story <ArrowUpRight /></Link></div></div></section>
  <section className="section section-dark"><div className="content-wrap split-content"><div><p className="eyebrow">Private events</p><h2>Big plans need a <em>great landing spot.</em></h2></div><div><p>Weddings, corporate events, rehearsal dinners, military reunions, fundraisers, holiday parties, concerts, and gatherings that deserve more than a back room.</p><p>Bring the people. We&apos;ll bring the spaces, food, drinks, and Aviator energy.</p><Link className="button" href="/private-events" data-analytics="home_private_event">Plan your event <ArrowUpRight /></Link></div></div></section>
  </>; }
