import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { InquiryForm } from "@/components/inquiry-form";
import { ArrowUpRight, MapPin } from "@/components/icons";
import { pageContent } from "@/data/site";
const faqs = [["Where is Aviator Brewing Company?", "The flagship brewery campus is at 688 Brewing Drive in Fuquay-Varina, North Carolina."], ["Do you have parking?", "Yes. The brewery campus has on-site parking, including accessible spaces. Other locations have nearby street or public parking."], ["Can I host a private event?", "Yes. Private events are hosted in the Ready Room, which holds up to 70 guests including the bar and includes a stage, microphone, full sound, and AV capability."], ["Are menus available on mobile?", "That is a core requirement of the new site. Final venue menus will be published as readable HTML rather than buried in PDFs."], ["How do I find current events?", "Visit the Events page for live music, specials, and upcoming gatherings."]];
export function generateStaticParams() { return Object.keys(pageContent).map((page) => ({ page })); }
export async function generateMetadata({ params }: { params: Promise<{ page: string }> }): Promise<Metadata> { const { page } = await params; const content = pageContent[page]; return { title: content?.title || "Aviator Brewing Company", description: content?.description }; }
export default async function ContentPage({ params }: { params: Promise<{ page: string }> }) { const page = (await params).page; const content = pageContent[page]; if (!content) notFound(); const formKind = content.form; return <><section className="page-hero"><div className="content-wrap"><p className="eyebrow">{content.eyebrow}</p><h1>{content.title}</h1><p>{content.description}</p><div className="hero-actions">{page === "shop" || page === "brewery" || page === "distillery" ? <a className="button" href="https://maps.google.com/?q=688+Brewing+Drive+Fuquay-Varina+NC+27526" target="_blank" rel="noreferrer" data-analytics={`${page}_directions`}><MapPin />{content.action}</a> : <a className="button" href={formKind ? "#inquiry" : "/about"} data-analytics={`${page}_action`}>{content.action} <ArrowUpRight /></a>}{page === "private-events" ? <a className="button button-outline" href="/media/menus/catering-events/food/1785010242714-Aviator_Ready_Room_Event_Menu_Clean.pdf" target="_blank" rel="noreferrer" data-analytics="private_events_onsite_buffet_menu">Onsite catering buffet menu <ArrowUpRight /></a> : null}</div></div></section><section className="section"><div className="content-wrap split-content"><div><p className="eyebrow">The Aviator way</p><h2>Craft, hospitality, and <em>a reason to get together.</em></h2></div><div><p>Every Aviator page is designed to answer the important questions quickly: where to go, what&apos;s happening, what to eat, and how to plan a visit. The content system keeps operational details centralized so teams can update them without hunting across a dozen pages.</p><p>As the final photography, menus, event feed, ordering tools, and booking integrations are connected, this page will become a focused conversion path for the people who need it.</p><Link className="section-link" href="/locations">Explore the locations <ArrowUpRight /></Link></div></div></section>{page === "faq" && <section className="section section-dark"><div className="content-wrap"><div className="story-timeline">{faqs.map(([question, answer]) => <div key={question}><strong>{question}</strong><span>{answer}</span></div>)}</div></div></section>}{formKind && <section id="inquiry" className="section section-dark"><div className="content-wrap"><div className="section-heading"><div><p className="eyebrow">{content.eyebrow}</p><h2>Let&apos;s get the <em>details moving.</em></h2></div></div><InquiryForm kind={formKind} /></div></section>}</>; }
