import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowUpRight, Calendar, MapPin } from "@/components/icons";
import { events } from "@/data/site";
export function generateStaticParams() { return events.map((event) => ({ slug: event.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const event = events.find((item) => item.slug === slug); return { title: event?.title || "Event" }; }
export default async function EventDetail({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const event = events.find((item) => item.slug === slug); if (!event) notFound(); return <><section className="detail-hero"><div className="detail-hero-image"><Image src={event.image} alt="Aviator event atmosphere" fill priority sizes="(max-width: 700px) 100vw, 50vw" /></div><div className="detail-hero-copy"><p className="eyebrow">{event.venue}</p><h1>{event.title}</h1><p>{event.description}</p><p><Calendar style={{ width: "1rem", verticalAlign: "text-bottom" }} /> <strong>{event.date}</strong> · {event.time}</p><div className="hero-actions"><a className="button" href="https://maps.google.com/?q=688+Brewing+Drive+Fuquay-Varina+NC+27526" target="_blank" rel="noreferrer" data-analytics={`event_directions_${event.slug}`}><MapPin />Get directions</a><Link className="button button-outline" href="/events" data-analytics={`event_calendar_${event.slug}`}>All events <ArrowUpRight /></Link></div></div></section><section className="section"><div className="content-wrap detail-grid"><article className="info-card"><p className="eyebrow">Add to your calendar</p><h2>Save the date.</h2><p>Calendar links and ticketing will connect here when the event platform credentials are available.</p><button className="button button-outline" type="button" data-analytics={`calendar_${event.slug}`}>Add to calendar</button></article><article className="info-card"><p className="eyebrow">Bring your crew</p><h2>Share the plan.</h2><p>Check the event listing before you go for any ticket, age, weather, parking, or schedule updates.</p><button className="button button-outline" type="button" data-analytics={`share_${event.slug}`}>Share event</button></article></div></section></>; }
